---
collections: 
  - name: community.general
    version: 13.3.0

  - name: ansible.posix
    version: 2.2.2

  - name: community.crypto
    version: 3.3.0

##Installed rhel-sytem-roles via RPM because I used free developer license to access everything

    
